Reduce cuda copying
ICRAR/leap-accelerate pull request #57
Opened 2020-11-02 02:25 UTC by calgray

Here done some cleanup around object encapsulation and a small improvement to cuda performance by only copying the avg_data buffer from gpu to cpu memory per direction. Benchmarking on my machine this improved:
* single direction SKA wall time 51.41s -> 50.53s
* multi direction SKA wall time 65.45s -> 57.68s

2020-11-02 02:26 UTC, calgray commented on src/icrar/leap-accelerate/algorithm/cuda/PhaseRotate.cu
> +        deviceMetadata.AvgDataToHost(hostMetadata.avg_data);
This is the performance enhancement

2020-11-02 08:01 UTC, rtobar requested changes
I looked at the changes and they look fine. I got a compilation error on my computer, I left a comment on the issue that needs to be solved. Once I get this up and running in hyades I'll run a new set of benchmarks.

2020-11-02 08:01 UTC, rtobar commented on src/icrar/leap-accelerate/algorithm/cuda/PhaseRotate.cu
>          );
Just above these lines there are a couple of `assert`s that fail to compile with the latest changes, they need to be changed to use `GetAvgData` and `GetVis`

2020-11-02 08:43 UTC, rtobar commented
I tested the changes now on hyades and indeed the phase rotation time goes down as expected :+1:. I left more comments on YAN-516.

2020-11-03 04:05 UTC, calgray commented
I might change one of the CI builds to Debug configuration as I often forget debug compiles extra lines of source

2020-11-03 04:05 UTC, rtobar approved these changes

2020-11-03 04:07 UTC, rtobar commented
Yeap, good idea, but remember that pure debug builds fail because they take too long to run the test; so maybe just add the `-DNDEBUG` into the `CMAKE_CXX_FLAGS` in the travis `cmake` invocation.

Anyway, I tried the changes in my computer and now it builds, so I've just approved this.

2020-11-03 05:08 UTC, merged